### ISSUE TITLE
Increased build time using `cargo-near-build` after #289 PR

### ISSUE THREAD

**Issue by frolvanya** [near/cargo-near#302]
Is it possible that this https://github.com/near/cargo-near/pull/289 PR increased building time? It runs slower on cargo-near-build v0.4.3 than on v0.4.3 + patching to the #292 PR

I have two workflow runs. The faster one was executed with 
```toml
[patch.crates-io]
cargo-near-build = { git = "https://github.com/near/cargo-near", rev = "2851dc60945bb9da25b38bd46b3ba7b445db33d6" }
```

https://github.com/Near-One/omni-bridge/actions/runs/13063259194/job/36450815503
https://github.com/Near-One/omni-bridge/actions/runs/13063409784/job/36451266656
